service: mes-microservices-starter-template

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}

package:
  individually: true

functions:
  getTestCentres:
    handler: src/functions/getTestCentres/framework/handler.handler
    events:
      - http:
          path: 'ref-data/test-centres'
          method: get
custom:
  stages:
    - dev
  webpack:
    webpackConfig: 'webpack-sls-offline.config.js'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
